# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: go-hello-world"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authex
  template:
    metadata:
      labels:
        app: authex
    spec:
      containers:
        - name: server
          # image: eu.gcr.io/iona-1/authex
          image: authex
          ports:
            - containerPort: 8401
          env:
            - name: AUTHEX_ADDRESS
              value: 0.0.0.0:8401
            - name: AUTHEX_PREFIX
              value: "node/"
            - name: AUTHEX_EXCHANGEURL
              value: http://tokenendpoint:3000/token
            - name: AUTHEX_CLIENTID
              value: iona-1
            - name: AUTHEX_CLIENTSECRET
              value: iona-1-password

          readinessProbe:
            tcpSocket:
              port: 8401
            initialDelaySeconds: 5
